# Generated by Django 4.2.17 on 2024-12-15 20:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("video_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedlink",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="sharedlink",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_links",
                to="video_app.video",
            ),
        ),
    ]
